// Shared table/column definitions for the full-data Excel export & import feature
// (server/src/routes/dataIo.js). Kept separate from the CRUD route registrations in
// app.js/contracts.js so this file is a single source of truth for "what is a sheet"
// without having to touch the already-working CRUD routes.

export const TABLE_DEFS = [
  {
    table: 'capacity_design',
    sheet: 'CapacityDesign',
    orderBy: 'sort_order, id',
    columns: [
      { key: 'seg_type', label: 'Type' },
      { key: 'segment_id', label: 'Segment ID' },
      { key: 'segment_label', label: 'Segment Label' },
      { key: 'design_capacity_gbps', label: 'Design Capacity (Gbps)', number: true },
      { key: 'sort_order', label: '정렬순서', number: true },
    ],
  },
  {
    table: 'capacity_phase',
    sheet: 'CapacityPhase',
    orderBy: 'sort_order, id',
    columns: [
      { key: 'segment_label', label: '구간' },
      { key: 'current_tbps', label: '현재 (Tbps)', number: true },
      { key: 'phase1_tbps', label: '1단계', number: true },
      { key: 'phase2_tbps', label: '2단계', number: true },
      { key: 'phase3_tbps', label: '3단계', number: true },
      { key: 'phase4_tbps', label: '4단계', number: true },
      { key: 'sort_order', label: '정렬순서', number: true },
    ],
  },
  {
    table: 'lightup_schedule',
    sheet: 'Lightup',
    orderBy: 'id',
    columns: [
      { key: 'schedule', label: 'Schedule' },
      { key: 'seg_type', label: 'Type' },
      { key: 'segment_id', label: 'Segment ID' },
      { key: 'if100g', label: '100G I/F (Gbps)', number: true },
      { key: 'if400g', label: '400G I/F (Gbps)', number: true },
      { key: 'unit_price', label: 'Unit Price / 100G ($)', number: true },
      { key: 'status', label: 'Status' },
      { key: 'complete_date', label: '완료일/예정일' },
      { key: 'note', label: '비고' },
    ],
  },
  {
    table: 'funnel',
    sheet: 'Funnel',
    orderBy: 'id',
    columns: [
      { key: 'no', label: 'No.', number: true },
      { key: 'customer', label: '고객명' },
      { key: 'a_end', label: 'A End' },
      { key: 'z_end', label: 'Z End' },
      { key: 'if100g', label: '100G I/F (Gbps)', number: true },
      { key: 'if400g', label: '400G I/F (Gbps)', number: true },
      { key: 'stage', label: 'Stage' },
      { key: 'priority', label: 'Priority' },
      { key: 'target_date', label: '목표일', date: true },
      { key: 'note', label: '비고' },
    ],
  },
  {
    table: 'kpis',
    sheet: 'KPI',
    orderBy: 'year',
    columns: [
      { key: 'year', label: '연도', number: true },
      { key: 'memo', label: '메모' },
    ],
  },
  {
    table: 'internal_demand_s',
    sheet: 'InternalDemand_S',
    orderBy: 'sort_order, id',
    columns: [
      { key: 'dls_code', label: 'DLS' },
      { key: 'segment_label', label: 'Segment' },
      { key: 'h1', label: 'H1', number: true },
      { key: 'h2', label: 'H2', number: true },
      { key: 'h3', label: 'H3', number: true },
      { key: 'h4', label: 'H4', number: true },
      { key: 'h5', label: 'H5', number: true },
      { key: 'h6', label: 'H6', number: true },
      { key: 'sort_order', label: '정렬순서', number: true },
    ],
  },
  {
    table: 'internal_demand_l',
    sheet: 'InternalDemand_L',
    orderBy: 'sort_order, id',
    columns: [
      { key: 'pop', label: 'PoP' },
      { key: 'segment_label', label: 'Segment' },
      { key: 'h1', label: 'H1', number: true },
      { key: 'h2', label: 'H2', number: true },
      { key: 'h3', label: 'H3', number: true },
      { key: 'h4', label: 'H4', number: true },
      { key: 'h5', label: 'H5', number: true },
      { key: 'sort_order', label: '정렬순서', number: true },
    ],
  },
  {
    table: 'contracts',
    sheet: 'Contracts',
    orderBy: 'id',
    columns: [
      { key: 'no', label: 'No.' },
      { key: 'customer', label: '고객명' },
      { key: 'contract_type', label: '계약방식' },
      { key: 'segment_s', label: 'Segment S' },
      { key: 'segment_l', label: 'Segment L' },
      { key: 'a_end', label: 'A End' },
      { key: 'z_end', label: 'Z End' },
      { key: 'if100g', label: '100G(Gbps)', number: true },
      { key: 'if400g', label: '400G(Gbps)', number: true },
      { key: 'currency', label: 'Currency' },
      { key: 'mrc', label: 'MRC', number: true },
      { key: 'otc', label: 'OTC', number: true },
      { key: 'om_annual', label: '연O&M', number: true },
      { key: 'contract_year', label: '계약연도', number: true },
      { key: 'duration_months', label: '기간(월)', number: true },
      { key: 'start_date', label: '시작일', date: true },
      { key: 'status', label: 'Status' },
      { key: 'cc_flag', label: 'CC여부' },
      { key: 'am', label: 'AM' },
    ],
  },
];
