// Bundles server/src/app.js (and every local + node_modules dependency it pulls
// in) into a single self-contained CJS file with no external requires besides
// Node built-ins and `pg-native` (an optional, never-invoked pg codepath).
//
// Why: Vercel's remote build for this npm-workspaces monorepo has repeatedly
// failed to include workspace-hoisted dependencies (express, jsonwebtoken, ...)
// in the deployed API function, causing intermittent ERR_MODULE_NOT_FOUND
// crashes in production, and running this bundler from a root `postinstall`
// hook hits the same problem (it can run before workspace deps finish
// installing). So the output (api/index.generated.cjs) is committed to git
// like any other build artifact: run `npm run build:api` and commit the
// result whenever server/src changes.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

await build({
  entryPoints: [path.join(rootDir, 'server/src/app.js')],
  outfile: path.join(rootDir, 'api/index.generated.cjs'),
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs',
  external: ['pg-native'],
  banner: { js: '// AUTO-GENERATED by scripts/build-api.mjs — do not edit directly.' },
  logLevel: 'info',
});
